inherit_gem:
  theforeman-rubocop:
    - strictest.yml

inherit_from: .rubocop_todo.yml

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation
  IndentationWidth: 2

Rails/SkipsModelValidations:
  Exclude:
    - 'db/migrate/**/*'
    - 'db/migrate_foreman/**/*'

Style/FormatStringToken:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'lib/foreman_puppet_enc/register.rb'
