require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-minitest

AllCops:
  TargetRubyVersion: 2.5
  TargetRailsVersion: 6.0
  Exclude:
    - 'node_modules/**/*'

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation
  IndentationWidth: 2

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/LineLength:
  Enabled: 111 # TODO: discuss and set this

Rails:
  Enabled: true

Style/Alias:
  EnforcedStyle: prefer_alias_method

# Don't enforce documentation
Style/Documentation:
  Enabled: false

# Don't enforce frozen string literals
Style/FrozenStringLiteralComment:
  Enabled: false

# Support both ruby19 and hash_rockets
Style/HashSyntax:
  Enabled: false
