inherit_gem:
  theforeman-rubocop:
    - strictest.yml

inherit_from: .rubocop_todo.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  Exclude:
    - 'vendor/**/*'

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation
  IndentationWidth: 2

Rails/SkipsModelValidations:
  Exclude:
    - 'db/migrate_foreman/**/*'

Style/FormatStringToken:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'config/*routes.rb'
    - 'lib/foreman_puppet_enc/register.rb'
