inherit_gem:
  theforeman-rubocop:
    - edge.yml

inherit_from: .rubocop_todo.yml

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation
  IndentationWidth: 2

Style/FormatStringToken:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys
