inherit_gem:
  theforeman-rubocop:
    - strictest.yml

inherit_from: .rubocop_todo.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: '2.7'
  Exclude:
    - 'vendor/bundle/**/*'
    
Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation
  IndentationWidth: 2

Naming/VariableNumber:
  Exclude:
    - 'test/**/*.rb'

Rails/SkipsModelValidations:
  Exclude:
    - 'db/migrate_foreman/**/*'

Style/FormatStringToken:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'config/*routes.rb'
    - 'lib/foreman_puppet/register.rb'
    - 'config/initializers/api_reroute.rb'

Gemspec/RequiredRubyVersion:
  Enabled: true
