module.exports = {
  parser: 'babel-eslint',
  parserOptions: {
    sourceType: 'module',
    ecmaFeatures: {
      jsx: true,
    },
  },
  plugins: ['spellcheck', 'react-hooks', 'import', 'react', 'jsx-a11y', 'jquery'],
  rules: {
    'spellcheck/spell-checker': [
      'error',
      {
        identifiers: false,
        ignoreRequire: true,
        skipWords: [
          'ansible',
          'camelcase',
          'checkbox',
          'csrf',
          'db',
          'dropdown',
          'enc',
          'flyout',
          'foreman',
          'hostgroup',
          'hostgroups',
          'href',
          'jed',
          'jsx',
          'katello',
          'noopener',
          'noreferrer',
          'nowrap',
          'pathname',
          'pid',
          'puppet',
          'puppetclass',
          'puppetclasses',
          'puppetserver',
          'redux',
          'repo',
          'scalprum',
          'smartclass',
          'smartproxy',
          'theforeman',
          'tfm',
          'tooltip',
          'unmount',
        ],
        minLength: 3,
      },
    ],
  },
};
